#ifndef _LCD_CNF_H
#define _LCD_CNF_H
#include <HAL/LCD/LCD.h>

/**
DEFINE NUMBER OF LINES THAT WILL USED IN LCD
	OPTIONS:
	1. ONE_LINE 
	2. TWO_LINES 
**/
#define NUMBER_OF_LINES TWO_LINES

/**
DEFINE TYPE OF FONT YOU WANT TO DISPLAY
	OPTIONS:
	1. DOT_5X7
	2. DOT_5X10
**/
#define CHARACTER_FONT SEVEN_DOTS

/**
DEFINE CONNECTION MODE YOU WILL USE 
	OPTIONS:
	1. FOUR_BIT_MODE 
	2. EIGHT_BIT_MODE 
**/
#define LCD_MODE LCD_8_BIT_MODE

/**
DEFINE DISPLAY STATE 
	OPTIONS:
	1. DISPLAY_ON
	2. DISPLAY_OFF 
**/
#define DISPLAY_STATE DISPLAY_ON

/**
DEFINE CURSOR STATE 
	OPTIONS:
	1. CURSOR_ON
	2. CURSOR_OFF 
**/
#define CURSOR_STATE CURSOR_ON

/**
DEFINE CURSOR BLINKING STATE 
	OPTIONS:
	1. CURSOR_BLINKING 
	2. CURSOR_NOT_BLINKING 
**/
#define CURSOR_BLINKING_STATE CURSOR_BLINKING



#endif
